---
title: "Class 6 R Functions"
author: "Barry Grant"
date: "1/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## File reading (again!)

Here we try to use **read.table()** and friends to input some example data into R

Lets insert a code chunk. 

```{r}
read.table("https://bioboot.github.io/bggn213_S18/class-material/test1.txt", header=TRUE, sep=",")
```

```{r}
data1 <- file1 <- "https://bioboot.github.io/bggn213_S18/class-material/test1.txt"
read.csv(file1)

```


```{r}
file2 <- "https://bioboot.github.io/bggn213_S18/class-material/test2.txt"
data2 <- read.table(file2, sep="$", header=TRUE)
data2
```

```{r}
file3 <- "https://bioboot.github.io/bggn213_S18/class-material/test3.txt"
data3 <- read.table(file3, header=FALSE)
data3
```

## R functions

My first function

```{r}
add <- function(x, y=1) {  
    # Sum the input x and y
    x + y
}
```

Lets use the **add()** function

```{r}
add(1)
```

```{r}
add(1,5)
```

```{r}
add( c(1,2,3,4) )
```

```{r}
add( c(1,2,3,4), 4)
```


```{r}
#add(1,2,2)
```

```{r}
#add(x=1, y="b")
```

# Our 2nd function

```{r}
rescale <- function(x) {
   rng <-range(x)
   (x - rng[1]) / (rng[2] - rng[1])
}

```

```{r}
rescale(1:10)
```

```{r}
# How would you get your function to work here…
rescale( c(1,2,NA,3,10) )

```

```{r}
x <- c(1,2,NA,3,10)
rng <-range(x)
rng
#   (x - rng[1]) / (rng[2] - rng[1])
```


```{r}
rescale2 <- function(x) {
   rng <-range(x, na.rm=TRUE)
   (x - rng[1]) / (rng[2] - rng[1])
}

```

```{r}
rescale2( c(1,2,NA,3,10) )
```

```{r}
#rescale2( c(1,2,NA,3,10, "bggn213") )
```

```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {

    rng <-range(x, na.rm=na.rm)
    print("Hello")

   answer <- (x - rng[1]) / (rng[2] - rng[1])
   
   #return(answer)

   print("is it me you are looking for?")

   if(plot) { 
      plot(answer, typ="b", lwd=4) 
     print("please done ever sing again!")
   }
   print("I can see it in ...")
   return(answer)

}

```


```{r}
rescale3( 1:10 , plot=TRUE)
```


## Using thr bio3d package 

```{r}
library(bio3d)
```


```{r}
pdb <- read.pdb("1hbs")
```

What is in this **pdb** thing?

```{r}
pdb
```


```{r}
# Can you improve this analysis code?
library(bio3d)
s1 <- read.pdb("4AKE")  # kinase with drug
s2 <- read.pdb("1AKE")  # kinase no drug
s3 <- read.pdb("1E4Y")  # kinase with drug

s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")

s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b

plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```


THis is some regular text but I can add data derived values in here like the number of atoms in this pdb `r nrow(s1$atom)`

```{r eval=FALSE}
# This is on purpose 
mean(c("barry", "is", "Tird"))
```















